### PR TITLE
Update INSTALL.md

### PR DESCRIPTION
**Pull request by skrish13**
easier copy paste for pip install packages :P

### CODE REVIEW

**Comment by ryana95** [comment]
where i can can receive my code for this open source project Facebook Thanks!

**Comment by Sotheangin934** [comment]
Thanks

**Comment by munnaakand** [comment]
My Gmail receiver

**Comment by shohidislam** [comment]
where i can can receive my code for this open source project Facebook Thanks!

**Comment by Sotheangin934** [comment]
Help

**Comment by ir413** [comment]
Thanks for the PR @skrish13. We recently switched to using a `requirements.txt` file to track Python dependencies so I think we can close this issue.

**Pull request closed without merging**
